SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS outgoing_letters;
DROP TABLE IF EXISTS number_sequences;
DROP TABLE IF EXISTS classification_items;
DROP TABLE IF EXISTS classification_groups;
DROP TABLE IF EXISTS archive_types;
DROP TABLE IF EXISTS letter_sensitivities;
DROP TABLE IF EXISTS letter_types;
DROP TABLE IF EXISTS numbering_rules;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS work_teams;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE work_teams (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER',
    work_team_id INT UNSIGNED NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    deleted_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_users_deleted_at (deleted_at),
    CONSTRAINT fk_users_team FOREIGN KEY(work_team_id) REFERENCES work_teams(id)
) ENGINE=InnoDB;

CREATE TABLE numbering_rules (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    unit_code VARCHAR(40) NOT NULL,
    pattern VARCHAR(200) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE letter_types (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    numbering_rule_id INT UNSIGNED NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT fk_type_rule FOREIGN KEY(numbering_rule_id) REFERENCES numbering_rules(id)
) ENGINE=InnoDB;

CREATE TABLE letter_sensitivities (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    prefix VARCHAR(10) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE archive_types (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    short_code CHAR(1) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

-- Full classification catalog imported from Kode.pdf
CREATE TABLE classification_groups (
  code VARCHAR(10) PRIMARY KEY,
  name TEXT NOT NULL,
  archive_type ENUM('SUBSTANTIF','FASILITATIF') NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_group_archive (archive_type,is_active,sort_order)
) ENGINE=InnoDB;

CREATE TABLE classification_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  group_code VARCHAR(10) NOT NULL,
  raw_code VARCHAR(10) NOT NULL,
  code VARCHAR(10) NOT NULL,
  name TEXT NOT NULL,
  description TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_classification_item (group_code,code),
  INDEX idx_classification_lookup (group_code,is_active,sort_order),
  CONSTRAINT fk_classification_group FOREIGN KEY(group_code) REFERENCES classification_groups(code)
) ENGINE=InnoDB;

INSERT INTO classification_groups(code,name,archive_type,sort_order,is_active) VALUES
('PS','PERUMUSAN KEBIJAKAN DI BIDANG STATISTIK MELIPUTI: METODOLOGI DAN INFORMASI STATISTIK, STATISTIK SOSIAL, STATISTIK PRODUKSI, STATISTIK DISTRIBUSI DAN JASA, NERACA DAN ANALISA STATISTIK','SUBSTANTIF',1,1),
('SS','SENSUS PENDUDUK, SENSUS PERTANIAN DAN SENSUS EKONOMI','SUBSTANTIF',2,1),
('VS','SURVEI','SUBSTANTIF',3,1),
('KS','KONSOLIDASI DATA STATISTIK','SUBSTANTIF',4,1),
('ES','EVALUASI DAN PELAPORAN SENSUS, SURVEI DAN KONSOLIDASI DATA','SUBSTANTIF',5,0),
('KU','KEUANGAN','FASILITATIF',10,1),
('KP','KEPEGAWAIAN','FASILITATIF',11,1),
('PR','PERENCANAAN','FASILITATIF',12,1),
('HK','HUKUM','FASILITATIF',13,1),
('OT','ORGANISASI DAN TATA LAKSANA','FASILITATIF',14,1),
('HM','HUBUNGAN MASYARAKAT','FASILITATIF',15,1),
('KA','KEARSIPAN','FASILITATIF',16,1),
('RT','KERUMAHTANGGAAN','FASILITATIF',17,1),
('PL','PERLENGKAPAN','FASILITATIF',18,1),
('DL','PENDIDIKAN DAN LATIHAN','FASILITATIF',19,1),
('PK','KEPUSTAKAAN','FASILITATIF',20,1),
('IF','INFORMATIKA','FASILITATIF',21,1),
('PW','PENGAWASAN','FASILITATIF',22,1),
('TS','TRANSFORMASI STATISTIK','FASILITATIF',23,1);

INSERT INTO classification_items(group_code,raw_code,code,name,description,sort_order,is_active) VALUES
('PS','000','000','Pengkajian dan Pengusulan Kebijakan',NULL,1,1),
('PS','100','100','Penyiapan Kebijakan',NULL,2,1),
('PS','200','200','Masukan dan Dukungan dalam Penyusunan Kebijakan',NULL,3,1),
('PS','300','300','Pengembangan desain dan standarisasi',NULL,4,1),
('PS','400','400','Penetapan Norma, Standar, Prosedur dan Kriteria (NSPK)',NULL,5,1),
('SS','000','000','PERENCANAAN',NULL,1,1),
('SS','100','100','PERSIAPAN SENSUS',NULL,2,1),
('SS','200','200','PELATIHAN/UJICOBA',NULL,3,1),
('SS','210','210','Pelatihan Instruktur',NULL,4,1),
('SS','220','220','Pelatihan Petugas',NULL,5,1),
('SS','230','230','Pelatihan Petugas Pengolahan',NULL,6,1),
('SS','300','300','PELAKSANAAN LAPANGAN',NULL,7,1),
('SS','310','310','Listing',NULL,8,1),
('SS','320','320','Pemilihan Sampel',NULL,9,1),
('SS','330','330','Pengumpulan Data',NULL,10,1),
('SS','340','340','Pemeriksaan Data',NULL,11,1),
('SS','350','350','Pengawasan Lapangan',NULL,12,1),
('SS','360','360','Monitoring Kualitas',NULL,13,1),
('SS','400','400','PENGOLAHAN',NULL,14,1),
('SS','410','410','Pengelolaan Dokumen (penerimaan/pengiriman, pengelompokkan/batching)',NULL,15,1),
('SS','420','420','Pemeriksaan Dokumen dan Pengkodean (editing/coding)',NULL,16,1),
('SS','430','430','Perekaman Data (entri/scanner)',NULL,17,1),
('SS','440','440','Tabulasi Data',NULL,18,1),
('SS','450','450','Pemeriksaan Tabulasi',NULL,19,1),
('SS','460','460','Laporan Konsistensi Tabulasi',NULL,20,1),
('SS','500','500','ANALISA DAN PENYAJIAN HASIL SENSUS',NULL,21,1),
('SS','510','510','Pembahasan Angka Hasil Pengolahan',NULL,22,1),
('SS','520','520','Penyusunan Angka Sementara',NULL,23,1),
('SS','530','530','Penyusunan Angka Tetap',NULL,24,1),
('SS','540','540','Penyusunan/Pembahasan Draft Publikasi',NULL,25,1),
('SS','550','550','Analisis Data Sensus',NULL,26,1),
('SS','560','560','Penyusunan Diseminasi Hasil Sensus',NULL,27,1),
('SS','600','600','DISEMINASI HASIL SENSUS',NULL,28,1),
('SS','610','610','Penyusunan bahan Diseminasi','1) Leaflet, booklet
2) Website
3) Penyusunan CD dan sejenisnya',29,1),
('SS','620','620','Sosialisasi hasil Sensus melalui berbagai Media',NULL,30,1),
('SS','630','630','Layanan Promosi Statistik',NULL,31,1),
('VS','000','000','PERENCANAAN',NULL,1,1),
('VS','10','010','Master Plan dan Network Planing',NULL,2,1),
('VS','20','020','Perumusan dan Penyusunan Bahan',NULL,3,1),
('VS','21','021','Penyiapan bahan penyusunan rancangan survei',NULL,4,1),
('VS','22','022','Penyusunan metode pencacahan survei',NULL,5,1),
('VS','23','023','Penentuan volume survei',NULL,6,1),
('VS','24','024','Penyusunan desain penarikan sampel',NULL,7,1),
('VS','25','025','Penyusunan Kerangka Sampel',NULL,8,1),
('VS','30','030','Studi pendahuluan (desk study)',NULL,9,1),
('VS','100','100','PERSIAPAN SURVEI',NULL,10,1),
('VS','110','110','Rancangan Organisasi',NULL,11,1),
('VS','120','120','Penyusunan Kuesioner',NULL,12,1),
('VS','130','130','Penyusunan Konsep dan Definisi',NULL,13,1),
('VS','140','140','Penyusunan Metodologi (organisasi, lapangan, ukuran statistik)',NULL,14,1),
('VS','150','150','Penyusunan Buku Pedoman (pencacahan, pengawasan, pengolahan)',NULL,15,1),
('VS','160','160','Penyusunan Peta Wilayah Kerja dan Muatan Peta Wilayah',NULL,16,1),
('VS','170','170','Penyusunan Pedoman Sosialisasi',NULL,17,1),
('VS','180','180','Penyusunan Program Pengolahan (rule validasi pemeriksaan entri tabulasi)',NULL,18,1),
('VS','190','190','Koordinasi Intern/Ekstern',NULL,19,1),
('VS','200','200','PELATIHAN/UJICOBA',NULL,20,1),
('VS','210','210','Pelatihan Instruktur',NULL,21,1),
('VS','220','220','Pelatihan Petugas',NULL,22,1),
('VS','230','230','Pelatihan Petugas Pengolahan',NULL,23,1),
('VS','240','240','Perancangan Tabel',NULL,24,1),
('VS','250','250','Pelaksanaan Ujicoba Kuesioner Sensus (meliputi reliabilitas kuesioner dan sistem pengolahan)',NULL,25,1),
('VS','260','260','Pelaksanaan Ujicoba Kuesioner Metodologi Sensus (meliputi ujicoba pelaksanaan pencacahan, organisasi dan jumlah sampel)',NULL,26,1),
('VS','300','300','PELAKSANAAN LAPANGAN',NULL,27,1),
('VS','310','310','Listing',NULL,28,1),
('VS','320','320','Pemilihan Sampel',NULL,29,1),
('VS','330','330','Pengumpulan Data',NULL,30,1),
('VS','340','340','Pemeriksaan Data',NULL,31,1),
('VS','350','350','Pengawasan Lapangan',NULL,32,1),
('VS','360','360','Monitoring Kualitas',NULL,33,1),
('VS','400','400','PENGOLAHAN',NULL,34,1),
('VS','410','410','Pengelolaan Dokumen (penerimaan/pengiriman, pengelompokkan/batching)',NULL,35,1),
('VS','420','420','Pemeriksaan Dokumen dan Pengkodean (editing/coding)',NULL,36,1),
('VS','430','430','Perekaman Data (entri/scanner)',NULL,37,1),
('VS','440','440','Tabulasi Data',NULL,38,1),
('VS','450','450','Pemeriksaan Tabulasi',NULL,39,1),
('VS','460','460','Laporan Konsistensi Tabulasi',NULL,40,1),
('VS','500','500','ANALISA DAN PENYAJIAN HASIL SENSUS',NULL,41,1),
('VS','510','510','Pembahasan Angka Hasil Pengolahan',NULL,42,1),
('VS','520','520','Penyusunan Angka Sementara',NULL,43,1),
('VS','530','530','Penyusunan Angka Prokyeksi/Ramalan',NULL,44,1),
('VS','540','540','Penyusunan Angka Tetap',NULL,45,1),
('VS','550','550','Penyusunan/Pembahasan Draft Publikasi',NULL,46,1),
('VS','560','560','Analisis Data Sensus',NULL,47,1),
('VS','570','570','Penyusunan Diseminasi Hasil Sensus',NULL,48,1),
('VS','600','600','DISEMINASI HASIL SENSUS',NULL,49,1),
('VS','610','610','Penyusunan bahan Diseminasi','1) Leaflet, booklet
2) Website
3) Penyusunan CD dan sejenisnya',50,1),
('VS','620','620','Sosialisasi hasil Sensus melalui berbagai Media',NULL,51,1),
('VS','630','630','Layanan Promosi Statistik',NULL,52,1),
('KS','000','000','KOMPILASI DATA',NULL,1,1),
('KS','100','100','ANALISIS DATA',NULL,2,1),
('KS','200','200','PENYUSUNAN PUBLIKASI',NULL,3,1),
('KU','0','000','PELAKSANAAN ANGGARAN',NULL,1,1),
('KU','10','010','Ketentuan/Peraturan Menteri Keuangan Menyangkut Pelaksanaan dan Penatausahaan',NULL,2,1),
('KU','100','100','REALISASI PENDAPATAN/PENERIMAAN NEGARA',NULL,3,1),
('KU','110','110','Surat Setoran Pajak (SSP)',NULL,4,1),
('KU','120','120','Surat Setoran Bukan Pajak (SSBP)',NULL,5,1),
('KU','130','130','Bukti Penerimaan Bukan Pajak (PNBP)',NULL,6,1),
('KU','140','140','Dana Bagi Hasil yang bersumber dari Pajak',NULL,7,1),
('KU','141','141','Pajak Bumi Bangunan',NULL,8,1),
('KU','142','142','Bea Perolehan Hak Atas Tanah dan Bangunan (BPHTB)',NULL,9,1),
('KU','143','143','Pajak Penghasilan (Pph) Pasal 21, 25 dan 29',NULL,10,1),
('KU','150','150','Bukti Setor Sisa Anggaran Lebih atau Bukti Setor Pengembalian Belanja (SSPB)',NULL,11,1),
('KU','160','160','Bunga dan/atau Jasa Giro pada Bank',NULL,12,1),
('KU','170','170','Piutang Negara',NULL,13,1),
('KU','180','180','Pengelolaan Investasi dan Penyertaan Modal',NULL,14,1),
('KU','200','200','PENGELOLAAN PERBENDAHARAAN',NULL,15,1),
('KU','210','210','Pejabat Penguji dan Penandatanganan SPM',NULL,16,1),
('KU','220','220','Bendahara Penerimaan',NULL,17,1),
('KU','230','230','Bendahara Pengeluaran',NULL,18,1),
('KU','240','240','Kartu Pengawasan Pembayaran Penghasilan Pegawai (KP4)',NULL,19,1),
('KU','250','250','Pengembalian Belanja',NULL,20,1),
('KU','260','260','Pembukuan Anggaran',NULL,21,1),
('KU','261','261','Buku Kas Umum (BKU)',NULL,22,1),
('KU','262','262','Buku Kas Pembantu (BKU)',NULL,23,1),
('KU','263','263','Kartu Realisasi Anggaran dan Pengawasan Realisasi Anggaran',NULL,24,1),
('KU','270','270','Berita Acara Pemeriksaan Kas',NULL,25,1),
('KU','280','280','Daftar Gaji/Kartu Gaji',NULL,26,1),
('KU','300','300','PENGELUARAN ANGGARAN','Naskah-naskah yang berkaitan dengan pelaksanaan anggaran pengeluaran mulai dari SPP-GU, SPP-LS, SPP-UP, SPP-TUP, SPM, SP2D, Juklak mekanisme pengelolaan APBN serta bahan nota keuangan',27,1),
('KU','310','310','Belanja Bahan',NULL,28,1),
('KU','320','320','Belanja Barang',NULL,29,1),
('KU','330','330','Belanja Jasa (Konsultan, Profesi)',NULL,30,1),
('KU','340','340','Belanja Perjalanan',NULL,31,1),
('KU','350','350','Belanja Pegawai',NULL,32,1),
('KU','360','360','Belanja Paket Meeting Dalam Kota',NULL,33,1),
('KU','370','370','Belanja Peket Meeting Luar Kota',NULL,34,1),
('KU','380','380','Belanja Akun Kombinasi',NULL,35,1),
('KU','400','400','VERIFIKASI ANGGARAN',NULL,36,1),
('KU','410','410','Surat Permintaan Pembayaran (SPP) beserta lampirannya',NULL,37,1),
('KU','420','420','Surat Perintah Membayar (SPM), Surat Perintah Pencairan Dana (SP2D)',NULL,38,1),
('KU','500','500','PELAPORAN',NULL,39,1),
('KU','510','510','Akuntansi Keuangan:',NULL,40,1),
('KU','511','511','Berita Acara Pemeriksaan Kas',NULL,41,1),
('KU','512','512','Kas/Register Penutupan Kas',NULL,42,1),
('KU','513','513','Laporan Pendapatan Negara',NULL,43,1),
('KU','514','514','Arsip Data Komputer',NULL,44,1),
('KU','520','520','Pengumpulan, Pemantauan, Evaluasi dan Laporan Keuangan',NULL,45,1),
('KU','521','521','Keadaan Kredit Anggaran (LKKA) Bulanan/Triwulanan/Bulanan','a. Laporan Realisasi Anggaran (RKA)
b. Neraca;
c. Laporan Arus Kas
d. Catatan Atas Laporan Keuangan (CALK)',46,1),
('KU','530','530','Rekonsilisasi Data Laporan Keuangan',NULL,47,1),
('KU','600','600','BANTUAN PINJAMAN LUAR NEGERI',NULL,48,1),
('KU','610','610','Permohonan Pinjaman Luar Negeri (Blue Book)',NULL,49,1),
('KU','620','620','Dokumen Kesanggupan negara donor (Gray Book)',NULL,50,1),
('KU','630','630','Memorandum of Understand (MOU) dan dokumen sejenisnya',NULL,51,1),
('KU','640','640','Loan Agreement Pinjaman/Hibah Luar Negeri (PHLN), legal opinion, surat-menyurat dengan lender, konsultan',NULL,52,1),
('KU','650','650','Alokasi dan Relokasi Penggunaan Dana Pinjaman/Hibah Luar Negeri',NULL,53,1),
('KU','660','660','Penarikan Dana Bantuan Luar Negeri (BLN)',NULL,54,1),
('KU','661','661','Aplikasi Penarikan Dana Bantuan Luar Negeri (BLN) berikut lampirannya :','a. Reimbursment;
b. Direct Payment/Transfer Procedure;
c. Special Comitment/L/C Opening;
d. Special Account/Imprest Fund.',55,1),
('KU','662','662','Otorisasi Penarikan Dana (Payment Advice)',NULL,56,1),
('KU','663','663','Replenisment (permintaan penarikan dana dari negara donor) meliputi :','a. No Objection Letter (NOL)
b. Notification of Contract
c. Withdrawal Authorization (WA)
d. Statement of Expenditur (SE)',57,1),
('KU','670','670','Realisasi Pencairan Dana Bantuan Luar Negeri','a. Surat Perintah Pencairan Dana (SP2D)
b. SPM beserta lampirannya : SPP, Kontrak, BA dan data pendukung lainnya',58,1),
('KU','680','680','Ketentuan/Peraturan yang Menyangkut Bantuan/Pinjaman Luar Negeri',NULL,59,1),
('KU','691','691','Staff Appraisal Report',NULL,60,1),
('KU','692','692','Report/Laporan yang terdiri dari :','a. Progress Report;
b. Monthly Report;
c. Quarter Report.',61,1),
('KU','693','693','Laporan Hutang Negara','a. Laporan Pembayaran Hutang Negara
b. Laporan Posisi Hutang Negara',62,1),
('KU','694','694','Completion Report/Annual Report.',NULL,63,1),
('KU','700','700','PENGELOLA APBN/DANA PINJAMAN/HIBAH LUAR NEGERI (PHLN)',NULL,64,1),
('KU','710','710','Keputusan Kepala BPS tentang Penetapan:',NULL,65,1),
('KU','711','711','Kuasa Pengguna Anggaran (KPA), Pejabat Pembuat Komitmen (PPK).',NULL,66,1),
('KU','712','712','Pejabat Pembuat Daftar Gaji;',NULL,67,1),
('KU','713','713','Penandatangan SPM;',NULL,68,1),
('KU','714','714','Bendahara Penerimaan/Pengeluaran, Pengelola Barang.',NULL,69,1),
('KU','800','800','SISTEM AKUNTANSI INSTANSI (SAI)',NULL,70,1),
('KU','810','810','Manual Implementasi Sistem Akuntansi Instansi (SAI)',NULL,71,1),
('KU','820','820','Arsip Data Komputer dan Berita Acara Rekonsiliasi',NULL,72,1),
('KU','830','830','a. Daftar Transaksi (DT), Pengeluaran (PK), Penerimaan (PN)','b. Dokumen Sumber (DS), Bukti Jurnal (BJ), Surat Tanda Setoran (STS)
c. Surat Setor Bukan Pajak (SSBP), Surat Perintah Pencairan Dana (SP2D)
d. SPM dalam Daftar Ringkasan Pengembalian dan Potongan dari Pengeluaran (SPDR)',73,1),
('KU','840','840','Listing (Daftar Rekaman Penerimaan) Buku Temuan dan Tindakan Lain (SAI)',NULL,74,1),
('KU','850','850','Laporan Realisasi Bulanan SAI',NULL,75,1),
('KU','860','860','Laporan Realisasi Triwulanan SAI dari Unit Akuntansi Wilayah (UAW) dan Gabungan semua UAW/Unit Akuntansi Kantor Pusat Instansi (UAKPI)',NULL,76,1),
('KU','900','900','PERTANGGUNGJAWABAN KEUANGAN NEGARA',NULL,77,1),
('KU','910','910','Laporan Hasil Pemeriksaan atas Laporan Keuangan oleh BPK RI',NULL,78,1),
('KU','920','920','Hasil Pengawasan dan Pemeriksaan Internal',NULL,79,1),
('KU','930','930','Laporan Aparat Pemeriksa Fungsional:',NULL,80,1),
('KU','931','931','Laporan Hasil Pemeriksaan (LHP)',NULL,81,1),
('KU','932','932','Memorandum Hasil Pemeriksaan (LHP)',NULL,82,1),
('KU','933','933','Tindak Lanjut/Tanggapan LHP',NULL,83,1),
('KU','940','940','Dokumentasi Penyelesaian Keuangan Negara:',NULL,84,1),
('KU','941','941','Tuntutan Perbendaharaan',NULL,85,1),
('KU','942','942','Tuntutan Ganti Rugi',NULL,86,1),
('KP','0','000','FORMASI PEGAWAI',NULL,1,1),
('KP','10','010','Usulan dari Unit Kerja',NULL,2,1),
('KP','20','020','Usulan Permintaan Formasi kepada Menpan dan Kepala BKN',NULL,3,1),
('KP','30','030','Persetujuan Menpan',NULL,4,1),
('KP','40','040','Penetapan Formasi',NULL,5,1),
('KP','50','050','Penetapan Formasi Khusus',NULL,6,1),
('KP','100','100','PENGADAAN DAN PENGANGKATAN PEGAWAI',NULL,7,1),
('KP','110','110','Proses Penerimaan Pegawai:',NULL,8,1),
('KP','111','111','Pengumuman',NULL,9,1),
('KP','112','112','Seleksi Administrasi',NULL,10,1),
('KP','113','113','Pemanggilan Peserta Tes',NULL,11,1),
('KP','114','114','Pelaksanaan Ujian (tertulis, psikotes, wawancara)',NULL,12,1),
('KP','115','115','Keputusan Hasil Ujian',NULL,13,1),
('KP','120','120','Penetapan Pengumuman Kelulusan',NULL,14,1),
('KP','130','130','Berkas Lamaran yang Tidak Diterima',NULL,15,1),
('KP','140','140','Nota Usul dan Kelengkapan Penetapan NIP',NULL,16,1),
('KP','150','150','Nota Usul Pengangkatan CPNS menjadi PNS',NULL,17,1),
('KP','160','160','Nota Usul Pengangkatan CPNS menjadi PNS lebih 2 Tahun',NULL,18,1),
('KP','170','170','SK CPNS/PNS Kolektif',NULL,19,1),
('KP','200','200','BERKAS PEGAWAI TIDAK TETAP/MITRA STATISTIK',NULL,20,1),
('KP','300','300','PEMBINAAN KARIR PEGAWAI',NULL,21,1),
('KP','310','310','Diklat Kursus/Tugas Belajar/Ujian Dinas/Izin Belajar Pegawai:',NULL,22,1),
('KP','311','311','Surat Perintah/Surat Tugas/SK/Surat Izin',NULL,23,1),
('KP','312','312','Laporan Kegiatan Pengembangan Diri',NULL,24,1),
('KP','313','313','Surat Tanda Tamat Pendidikan dan Pelatihan',NULL,25,1),
('KP','320','320','Ujian Kompetensi',NULL,26,1),
('KP','321','321','Assesment Tes Pegawai',NULL,27,1),
('KP','322','322','Pemetaan/Mapping Talent Pegawai',NULL,28,1),
('KP','330','330','Daftar Penilaian Pelaksanaan Pekerjaan (DP3) dan Sasaran Kinerja Pegawai (SKP)',NULL,29,1),
('KP','340','340','Pakta Integritas Pegawai',NULL,30,1),
('KP','350','350','Laporan Hasil Kekayaan Penyelenggaraan Negara (LHKPN)',NULL,31,1),
('KP','360','360','Daftar Usul Penetapan Angka Kredit Fungsional',NULL,32,1),
('KP','370','370','Disiplin Pegawai:',NULL,33,1),
('KP','371','371','Daftar Hadir',NULL,34,1),
('KP','372','372','Rekapitulasi Daftar Hadir',NULL,35,1),
('KP','380','380','Berkas Hukuman Disiplin',NULL,36,1),
('KP','390','390','Penghargaan dan Tanda Jasa (Satya Lencana/Bintang Jasa)',NULL,37,1),
('KP','400','400','PENYELESAIAN PENGELOLAAN KEBERATAN PEGAWAI',NULL,38,1),
('KP','500','500','MUTASI PEGAWAI',NULL,39,1),
('KP','510','510','Alih Status, Pindah Instansi, Pindah Wilayah Kerja, Diperbantukan, Dipekerjakan, Penugasan Sementara, Mutasi Antar Perwakilan, Mutasi ke dan dari perwakilan Sementara, Mutasi Antar Unit',NULL,40,1),
('KP','520','520','Nota Persetujuan/Pertimbangan Kepala BKN',NULL,41,1),
('KP','530','530','Mutasi Keluarga:',NULL,42,1),
('KP','531','531','Surat Izin Pernikahan/Perceraian',NULL,43,1),
('KP','532','532','Surat Penolakan Izin Pernikahan/Perceraian',NULL,44,1),
('KP','533','533','Akte Nikah/Cerai',NULL,45,1),
('KP','534','534','Surat Keterangan Meninggal Dunia',NULL,46,1),
('KP','540','540','Usul Kenaikan Pengkat/Golongan/Jabatan',NULL,47,1),
('KP','550','550','Usul Pengangkatan dan Pemberhentian dalam Jabatan Struktural/Fungsional',NULL,48,1),
('KP','560','560','Usul Penetapan Perubahan Data Dasar/Status/Kedudukan Hukum Pegawai',NULL,49,1),
('KP','570','570','Peninjauan Masa Kerja',NULL,50,1),
('KP','580','580','Berkas Baperjakat',NULL,51,1),
('KP','600','600','ADMINISTRASI PEGAWAI',NULL,52,1),
('KP','610','610','Dokumentasi Identitas Pegawai:',NULL,53,1),
('KP','611','611','Usul Penetapan Karpeg/KPE/Karis/Karsu',NULL,54,1),
('KP','612','612','Keanggotaan Organisasi Profesi/Kedinasan',NULL,55,1),
('KP','613','613','Laporan Pajak Penghasilan Pribadi (LP2P)',NULL,56,1),
('KP','614','614','Keterangan Penerimaan Penghasilan Pegawai (KP4)',NULL,57,1),
('KP','620','620','Berkas Pegawai dan Daftar Urut Kepangkatan (DUK)',NULL,58,1),
('KP','630','630','Berkas Perorangan Pegawai Negeri Sipil:','a. Nota Penetapan NIP dan kelengkapannya
b. Nota Persetujuan/Pertimbangan Kepala BKN
c. SK Pengangkatan CPNS
d. Hasil Pengujian Kesehatan
e. SK Pengangkatan PNS
f. SK Peninjauan Masa Kerja
g. SK Kenaikan Pangkat
h. Surat Pernyataan Melaksanakan Tugas/Menduduki Jabatan/Surat Pernyataan Pelantikan
i. SK Pengangkatan Dalam atau Pemberhentian Dari Jabatan Struktural/Fungsional
j. SK Perpindahan Wilayah Kerja
k. SK Perpindahan Antar Instansi
l. SK Cuti di Luar Tanggungan Negara (CLTN)
m. Berita Acara Pemeriksaan
n. SK Hukuman Jabatan/Hukuman Disiplin PNS
o. SK Perbantuan/Dipekerjakan Diluar Instansi Induk
p. SK Penarikan Kembali dari Perbantuan/Dipekerjakan
q. SK Pemberian Uang Tunggu
r. SK Pembebasan Dari Jabatan Organik Karena Diangkat Sebagai Pejabat Negara
s. SK Pengalihan PNS
t. SK Pemberhentian sebagai PNS
u. SK Pemberhentian Sementara
v. Surat Keterangan Pernyataan Hilang
w. Surat Keterangan Kembalinya PNS Yang Dinyatakan Hilang
x. SK Penggantian Nama
y. Surat Perbaikan Tanggal Tahun Kelahiran
z. Akta Nikah/Cerai
aa. Akta Kelahiran
bb. Isian Formulir PUPNS
cc. Berita Acara Pengambilan Sumpah/Janji PNS dari Jabatan
dd. Surat Permohonan Menjadi Anggota Parpol
ee. Surat Keterangan Mutasi Keluarga
ff. Surat Keterangan Meninggal Dunia
gg. Surat Keterangan Peningkatan Pendidikan
hh. Penetapan Angka Kredit Jabatan Fungsional
ii. Surat Keterangan Hasil Penelitian Khusus
jj. Surat Pemberitahuan Kenaikan Gaji Berkala
kk. Surat Tugas/Izin Belajar Dalam/Luar Negeri
ll, Surat Izin Bepergian ke Luar Negeri
mm. Kartu Pendaftaran Ulang (Kardaf) PNS
nn. Ijazah/Sertifikat
oo. SK Penempatan/Penarikan Pegawai
pp. SK Pengangkatan Pada Jabatan Diluar Instansi Induk
qq. Surat Pertimbangan Status TNI
rr. SK Pengaktifan Kembali Sebagai PNS
ss. Surat Pernyataan Pengunduran Diri Dari Jabatan Organik Karena Dicalonkan Sebagai Kepala/Wakil Kepala Daerah',59,1),
('KP','640','640','Berkas Perseorangan Pejabat Negara',NULL,60,1),
('KP','641','641','Kepala BPS;',NULL,61,1),
('KP','642','642','Pejabat Negara Lain yang ditentukan oleh Undang-Undang',NULL,62,1),
('KP','650','650','Surat Perintah Dinas/Surat Tugas',NULL,63,1),
('KP','660','660','Berkas Cuti Pegawai',NULL,64,1),
('KP','661','661','Cuti Sakit',NULL,65,1),
('KP','662','662','Cuti Bersalin',NULL,66,1),
('KP','663','663','Cuti Tahunan',NULL,67,1),
('KP','664','664','Cuti Alasan Penting',NULL,68,1),
('KP','665','665','Cuti Luar Tanggungan Negara (CLTN)',NULL,69,1),
('KP','700','700','KESEJAHTERAAN PEGAWAI',NULL,70,1),
('KP','710','710','Berkas Tentang Layanan Tunjangan/Gaji',NULL,71,1),
('KP','720','720','Berkas Tentang Layanan Pemeliharaan Kesehatan Pegawai',NULL,72,1),
('KP','730','730','Berkas Tentang Layanan Asuransi Pegawai',NULL,73,1),
('KP','740','740','Berkas Tentang Layanan Bantuan Sosial',NULL,74,1),
('KP','750','750','Berkas Tentang Layanan Olahraga Dan Rekreasi',NULL,75,1),
('KP','760','760','Berkas Tentang Layanan Pengurusan Jenazah',NULL,76,1),
('KP','770','770','Berkas Tentang Layanan Organisasi Non Kedinasan (Korpri, Dharma Wanita, Koperasi)',NULL,77,1),
('KP','800','800','PEMBERHENTIAN PEGAWAI TANPA HAK PENSIUN',NULL,78,1),
('KP','900','900','USUL PEMBERHENTIAN DAN PENETAPAN PENSIUN PEGAWAI/JANDA/DUDA & PNS YANG TEWAS',NULL,79,1),
('PR','0','000','POKOK-POKOK KEBIJAKAN DAN STRATEGI PEMBANGUNAN',NULL,1,1),
('PR','10','010','Pengumpulan Data',NULL,2,1),
('PR','20','020','Rencana Pembangunan Jangka Panjang (RPJP)',NULL,3,1),
('PR','30','030','Rencana Pembangunan Jangka Panjang (RPJP)',NULL,4,1),
('PR','40','040','Rencana Kerja Pemerintah (RKP)',NULL,5,1),
('PR','50','050','Penyelenggaraan Musyawarah Perencanaan Pembangunan (Musrenbang)',NULL,6,1),
('PR','100','100','PENYUSUNAN RENCANA',NULL,7,1),
('PR','110','110','Rencana Kegiatan Teknis',NULL,8,1),
('PR','120','120','Rencana Kegiatan Non Teknis',NULL,9,1),
('PR','130','130','Keterpaduan Rencana Teknis dan Non Teknis',NULL,10,1),
('PR','200','200','USULAN RENCANA DAN PROGRAM KERJA','Nama level 200 dipulihkan dari ringkasan klasifikasi pada bagian tabel bantu dalam dokumen yang sama.',11,1),
('PR','210','210','Usulan Unit Kerja beserta data pendukungnya',NULL,12,1),
('PR','220','220','Program Kerja Tahunan Unit Kerja',NULL,13,1),
('PR','230','230','Program Kerja Tahunan Instansi/Lembaga',NULL,14,1),
('PR','300','300','RENCANA ANGGARAN PENDAPATAN DAN BELANJA NEGARA (RAPBN)',NULL,15,1),
('PR','310','310','Penyusunan RAPBN',NULL,16,1),
('PR','311','311','Arah Kebijakan Umum, Strategi, Prioritas dan Renstra :','a. Rencana Kerja
b. Rencana Kerja Pemerintah',17,1),
('PR','312','312','Rencana Kerja dan Anggaran Kementrian/Lembaga (RKAKL)',NULL,18,1),
('PR','313','313','Rencana Satuan Anggaran Per Satuan Kerja (SAPSK), Satuan Rincian Alokasi Anggaran (SRAA)',NULL,19,1),
('PR','320','320','Penyampaian APBN kepada DPR RI',NULL,20,1),
('PR','321','321','Nota Keuangan Pemerintah dan Rancangan Undang-Undang RAPBN :','a. Nota Keuangan Pemerintah
b. Materi RAPBN dari Lembaga Negara dan Badan Pemerintah (RASKIP)',21,1),
('PR','322','322','Pembahasan RAPBN oleh Komisi DPR RI',NULL,22,1),
('PR','323','323','Risalah Rapat Dengar Pendapat dengan DPR RI',NULL,23,1),
('PR','324','324','Nota Jawaban DPR RI',NULL,24,1),
('PR','330','330','Undang-Undang Anggaran Pendapatan dan Belanja Negara (APBN) dan Rencana Pembangunan Tahunan (REPETA)',NULL,25,1),
('PR','400','400','PENYUSUNAN ANGGARAN PENDAPATAN NEGARA (APBN)',NULL,26,1),
('PR','410','410','Ketetapan Pagu Indikatif/Pagu Sementara',NULL,27,1),
('PR','420','420','Ketetapan Pagu Definitif',NULL,28,1),
('PR','430','430','Rencana Kerja Anggaran (RKA) Lembaga Negara dan Badan Pemerintah (LNBP)',NULL,29,1),
('PR','440','440','Daftar Isian Pelaksanaan Anggaran (DIPA) dan Revisinya',NULL,30,1),
('PR','450','450','Petunjuk Operasional Kegiatan (POK) dan Revisinya',NULL,31,1),
('PR','460','460','Petunjuk Teknis Tata Laksana Keterpaduan Kegiatan dan Pengelolaan Anggaran',NULL,32,1),
('PR','470','470','Target Penerimaan Negara Bukan Pajak',NULL,33,1),
('PR','500','500','PENYUSUNAN STANDAR HARGA MONITORING PROGRAM',NULL,34,1),
('PR','510','510','Pedoman Pengumpulan dan Pengolahan Data Standar Harga',NULL,35,1),
('PR','520','520','Pedoman Teknis Monitoring Program dan Kegiatan',NULL,36,1),
('PR','530','530','Pedoman Teknis Evaluasi dan Pelaporan Program',NULL,37,1),
('PR','600','600','LAPORAN',NULL,38,1),
('PR','610','610','Laporan Khusus',NULL,39,1),
('PR','611','611','Pemantauan Prioritas',NULL,40,1),
('PR','612','612','Laporan Pelaksanaan Kegiatan Atas Permintaan Eksternal',NULL,41,1),
('PR','613','613','Laporan Atas Pelaksanaan Kegiatan/Program Tertentu',NULL,42,1),
('PR','614','614','Rapat Dengar Pendapat dengan DPR RI',NULL,43,1),
('PR','620','620','Laporan Progress Report',NULL,44,1),
('PR','630','630','Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP)',NULL,45,1),
('PR','640','640','Laporan Berkala (harian, mingguan, bulanan, triwulanan, semesteran, tahunan)',NULL,46,1),
('PR','700','700','EVALUASI PROGRAM',NULL,47,1),
('PR','710','710','Evaluasi Program Unit Kerja',NULL,48,1),
('PR','720','720','Evaluasi Program Lembaga/Instansi',NULL,49,1),
('HK','0','000','PROGRAM LEGISLASI',NULL,1,1),
('HK','10','010','Bahan/Materi Program Legislasi Nasional dan Instansi',NULL,2,1),
('HK','20','020','Program Legislasi Lembaga/Instansi',NULL,3,1),
('HK','100','100','PERATURAN PIMPINAN LEMBAGA/INSTANSI','Termasuk rancangan awal sampai dengan rancangan akhir dan telaah hukum''',4,1),
('HK','110','110','Peraturan Kepala BPS',NULL,5,1),
('HK','200','200','KEPUTUSAN/KETETAPAN PIMPINAN LEMBAGA/INSTANSI','Termasuk rancangan awal sampai dengan rancangan akhir dan telaah hukum''',6,1),
('HK','300','300','INSTRUKSI SURAT EDARAN','Termasuk rancangan awal sampai dengan rancangan akhir dan telaah hukum''',7,1),
('HK','310','310','Instruksi/Surat Edaran Kepala BPS',NULL,8,1),
('HK','320','320','Instruksi/Surat Edaran Pejabat Tinggi Madya dan Pejabat Tinggi Pratama',NULL,9,1),
('HK','400','400','SURAT PERINTAH',NULL,10,1),
('HK','410','410','Surat Perintah Kepala BPS',NULL,11,1),
('HK','420','420','Surat Perintah Pejabat Madya',NULL,12,1),
('HK','430','430','Surat Perintah Pejabat Pratama',NULL,13,1),
('HK','500','500','PEDOMAN','Standar/Pedoman/Prosedur Kerja/Petunjuk Pelaksanaan/Petunjuk Teknis yang Bersifat Nasional/Regional/Instantional termasuk rancangan awal sampai dengan rancangan akhir',14,1),
('HK','600','600','NOTA KESEPAHAMAN',NULL,15,1),
('HK','610','610','Dalam Negeri',NULL,16,1),
('HK','620','620','Luar Negeri',NULL,17,1),
('HK','700','700','DOKUMENTASI HUKUM','Undang-undang Peraturan Pemerintah, Keputusan Presiden dan peraturan-peraturan lain di luar produk hukum BPS yang dijadikan referensi',18,1),
('HK','800','800','SOSIALISASI/PENYULUHAN/PEMBINAAN HUKUM',NULL,19,1),
('HK','810','810','Berkas yang berhubungan dengan kegiatan sosialisasi atau penyuluhan hukum',NULL,20,1),
('HK','820','820','Laporan hasil pelaksanaan sosialisasi penyuluhan hukum',NULL,21,1),
('HK','900','900','BANTUAN KONSULTASI HUKUM/ADVOKASI','Berkas tentang pemberian bantuan/konsultasi hukum (Pidana, Perdata, Tata Usaha Negara dan Agama)',22,1),
('HK','1000','1000','KASUS/SENGKETA HUKUM',NULL,23,1),
('HK','1010','1010','Pidana','Berkas tentang kasus/sengketa pidana, baik kejahatan maupun pelanggaran',24,1),
('HK','1011','1011','Proses verbal mulai dari penyelidikan, penyidikan sampai dengan vonis',NULL,25,1),
('HK','1012','1012','Berkas pembelaan dan bantuan hukum',NULL,26,1),
('HK','1013','1013','Telaah hukum dan opini hukum',NULL,27,1),
('HK','1020','1020','Perdata',NULL,28,1),
('HK','1021','1021','Proses gugatan sampai dengan putusan',NULL,29,1),
('HK','1022','1022','Berkas pembelaan dan bantuan hukum',NULL,30,1),
('HK','1023','1023','Telaah hukum dan opini hukum',NULL,31,1),
('HK','1030','1030','Tata Usaha Negara',NULL,32,1),
('HK','1031','1031','Proses gugatan sampai dengan putusan',NULL,33,1),
('HK','1032','1032','Berkas pembelaan dan bantuan hukum',NULL,34,1),
('HK','1033','1033','Telaah hukum dan opini hukum',NULL,35,1),
('HK','1040','1040','Arbitrase',NULL,36,1),
('HK','1041','1041','Proses gugatan sampai dengan putusan',NULL,37,1),
('HK','1042','1042','Berkas pembelaan dan bantuan hukum',NULL,38,1),
('HK','1043','1043','Telaah hukum dan opini hukum',NULL,39,1),
('OT','0','000','ORGANISASI','Meliputi hal-hal yang berkenaan dengan masalah bahan persiapan dan penyusunan organisasi BPS dan unit kerja dibawahnya',1,1),
('OT','10','010','Pembentukan Organisasi',NULL,2,1),
('OT','20','020','Pengubahan Organisasi',NULL,3,1),
('OT','30','030','Pembubaran Organisasi',NULL,4,1),
('OT','40','040','Evaluasi Kelembagaan','Meliputi naskah-naskah yang berkaitan dengan penilaian dan penyempurnaan organisasi',5,1),
('OT','50','050','Uraian Jabatan:','Meliputi hal-hal yang berkenaan dengan masalah klasifikasi kepegawaian/pekerjaan, penelitian, jabatan dan analisa jabatan',6,1),
('OT','100','100','TATA LAKSANA',NULL,7,1),
('OT','110','110','Standar Kompetensi Jabatan Struktural dan Fungsional','Meliputi hal-hal yang berkenaan dengan standar kompetensi jabatan struktural dan jabatan fungsional',8,1),
('OT','120','120','Tata Hubungan Kerja','Meliputi hal-hal yang berkenaan dengan masalah penyusunan tata hubungan kerja baik intern maupu ekstern BPS',9,1),
('OT','130','130','Sistem dan Prosedur','Meliputi hal-hal yang berkenaan dengan masalah penelaahan tata cara dan metode kegiatan di bidang perstatistikan
Kode Klasifikasi',10,1),
('HM','0','000','KEPROTOKOLAN',NULL,1,1),
('HM','10','010','Penyelenggaraan acara kedinasan (upacara, pelantikan, peresmian dan jamuan termasuk acara peringatan hari-hari besar)',NULL,2,1),
('HM','20','020','Agenda kegiatan pimpinan',NULL,3,1),
('HM','30','030','Kunjungan dinas',NULL,4,1),
('HM','031','031','Kunjungan dinas dalam dan luar negeri',NULL,5,1),
('HM','032','032','Kunjungan dinas pimpinan lembaga/instansi',NULL,6,1),
('HM','033','033','Kunjungan dinas pejabat lain/pegawai',NULL,7,1),
('HM','40','040','Buku Tamu',NULL,8,1),
('HM','50','050','Daftar nama/alamat kantor/pejabat',NULL,9,1),
('HM','100','100','LIPUTAN MEDIA MASSA','Liputan kegiatan dinas pimpinan acara kedinasan dan peristiwa-peristiwa bidang masing-masing yang diliput oleh media massa (cetak dan elektronik)',10,1),
('HM','200','200','PENYAJIAN INFORMASI KELEMBAGAAN','Penyajian informasi kelembagaan, pengumpulan, pengolahan dan penyajian informasi kelembagaan',11,1),
('HM','210','210','Kliping Koran',NULL,12,1),
('HM','220','220','Penerbitan majalah, buletin, koran dan jurnal',NULL,13,1),
('HM','230','230','Brosur/leaflet/poster/plakat',NULL,14,1),
('HM','240','240','Pengumuman/pemberitaan',NULL,15,1),
('HM','300','300','HUBUNGAN ANTAR LEMBAGA',NULL,16,1),
('HM','310','310','Hubungan antar lembaga pemerintah',NULL,17,1),
('HM','320','320','Hubungan dengan organisasi sosial/LSM',NULL,18,1),
('HM','330','330','Hubungan dengan perusahaan',NULL,19,1),
('HM','340','340','Hubungan dengan perguruan tinggi/sekolah: magang, Pendidikan Sistem Ganda, Praktek Kerja Lapangan (PKL)',NULL,20,1),
('HM','350','350','Forum Kehumasan (Bakohumas/Perhumas)',NULL,21,1),
('HM','360','360','Hubungan dengan media massa:','a. Siaran pers/konferensi pers/pers release
b. Kunjungan wartawan/peliputan
c. Wawancara',22,1),
('HM','400','400','DENGAR PENDAPAT/HEARING DPR',NULL,23,1),
('HM','500','500','PENYIAPAN BAHAN MATERI PIMPINAN',NULL,24,1),
('HM','600','600','PUBLIKASI MELALUI MEDIA CETAK MAUPUN ELEKTRONIK',NULL,25,1),
('HM','700','700','PAMERAN/SAYEMBARA/LOMBA/FESTIVAL, PEMBUATAN SPANDUK DAN IKLAN',NULL,26,1),
('HM','800','800','PENGHARGAAN/KENANG-KENANGAN/CINDERA MATA',NULL,27,1),
('HM','900','900','UCAPAN TERIMA KASIH, UCAPAN SELAMAT, BELA SUNGKAWA, PERMOHONAN MAAF',NULL,28,1),
('KA','0','000','PENCETAKAN',NULL,1,1),
('KA','10','010','Penyiapan pembuatan buku kerja dan kalender BPS',NULL,2,1),
('KA','20','020','Penerimaan permintaan mencetak dan naskah yang akan dicetak',NULL,3,1),
('KA','30','030','Menyusun perencanaan cetak',NULL,4,1),
('KA','40','040','Pencetakan naskah, surat, dokumen secara digital dan risograph',NULL,5,1),
('KA','100','100','PENGURUSAN SURAT',NULL,6,1),
('KA','110','110','Surat Masuk/Surat Keluar',NULL,7,1),
('KA','120','120','Penggunaan Aplikasi Surat Menyurat',NULL,8,1),
('KA','200','200','PENGELOLAAN ARSIP DINAMIS',NULL,9,1),
('KA','210','210','Penyusunan Sistem Arsip',NULL,10,1),
('KA','220','220','Penciptaan dan Pemberkasan Arsip',NULL,11,1),
('KA','230','230','Pengolahan Data Base menjadi Informasi',NULL,12,1),
('KA','240','240','Alih Media',NULL,13,1),
('KA','300','300','PENYIMPANAN DAN PEMELIHARAAN ARSIP',NULL,14,1),
('KA','310','310','Daftar Arsip',NULL,15,1),
('KA','320','320','Pemeliharaan Arsip dan Ruang Penyimpanan (seperti kegiatan fumigasi)',NULL,16,1),
('KA','330','330','Daftar Pencarian Arsip',NULL,17,1),
('KA','340','340','Daftar Arsip Informasi Publik',NULL,18,1),
('KA','350','350','Daftar Arsip Vital/Aset',NULL,19,1),
('KA','360','360','Layanan Arsip (peminjam, pengguna arsip)',NULL,20,1),
('KA','370','370','Persetujuan Jadwal Retensi Arsip',NULL,21,1),
('KA','400','400','PEMINDAHAN ARSIP',NULL,22,1),
('KA','410','410','Pemindahan Arsip Inaktif',NULL,23,1),
('KA','420','420','Daftar Arsip yang Dipindahkan',NULL,24,1),
('KA','500','500','PEMUSNAHAN ARSIP YANG TIDAK BERNILAI GUNA',NULL,25,1),
('KA','510','510','Berita Acara Pemusnahan',NULL,26,1),
('KA','520','520','Daftar Arsip yang Dimusnahkan',NULL,27,1),
('KA','530','530','Rekomendasi/Pertimbangan/Pemusnahan Arsip dari ANRI',NULL,28,1),
('KA','540','540','Surat Keputusan Pemusnahan',NULL,29,1),
('KA','600','600','PENYERAHAN ARSIP STATIS',NULL,30,1),
('KA','610','610','Berita Acara Serah Terima Arsip',NULL,31,1),
('KA','620','620','Daftar Arsip yang Diserahkan',NULL,32,1),
('KA','700','700','PEMBINAAN KEARSIPAN',NULL,33,1),
('KA','710','710','Pembinaan Arsiparis',NULL,34,1),
('KA','720','720','Apresiasi/Sosialisasi/Penyuluhan Kearsipan, Diklat Profesi',NULL,35,1),
('KA','730','730','Bimbingan Teknis',NULL,36,1),
('KA','740','740','Penilaian dan sertifikasi SDM kearsipan',NULL,37,1),
('KA','750','750','Supervisi dan Monitoring',NULL,38,1),
('KA','760','760','Penilaian dan Akreditasi Unit Kerja Kearsipan',NULL,39,1),
('KA','770','770','Implementasi Pengelolaan Arsip Elektronik',NULL,40,1),
('KA','780','780','Penghargaan Kearsipan',NULL,41,1),
('KA','790','790','Pengawasan Kearsipan',NULL,42,1),
('RT','0','000','TELEKOMUNIKASI','Administrasi penggunaan/langganan peralatan telekomunikasi meliputi : telepon, radio, teleks, TV label dan internet',1,1),
('RT','100','100','ADMINISTRASI PENGGUNAAN FASILITAS KANTOR','Administrasi penggunaan fasilitas kantor meliputi permintaan dan penggunaan ruang, gedung, kendaraan, wisma rumah dinas dan fasilitas kantor lainnya',2,1),
('RT','200','200','PENGURUSAN KENDARAAN DINAS',NULL,3,1),
('RT','210','210','Pengurusan Surat Kendaraan Dinas',NULL,4,1),
('RT','220','220','Pemeliharaan dan Perbaikan',NULL,5,1),
('RT','230','230','Pengurusan Kehilangan dan Masalah Kendaraan',NULL,6,1),
('RT','300','300','PEMELIHARAAN GEDUNG DAN TAMAN',NULL,7,1),
('RT','310','310','Pertamanan/Lanscaping',NULL,8,1),
('RT','320','320','Penghijauan',NULL,9,1),
('RT','330','330','Perbaikan Gedung',NULL,10,1),
('RT','340','340','Perbaikan Rumah Dinas/Wisma',NULL,11,1),
('RT','350','350','Kebersihan Gedung dan Taman',NULL,12,1),
('RT','400','400','PENGELOLAAN JARINGAN LISTRIK, AIR, TELEPON DAN KOMPUTER',NULL,13,1),
('RT','410','410','Perbaikan/Pemeliharaan',NULL,14,1),
('RT','420','420','Pemasangan',NULL,15,1),
('RT','500','500','KETERTIBAN DAN KEAMANAN',NULL,16,1),
('RT','510','510','Pengamanan, penjagaan dan pengawasan terhadap pejabat, kantor, dan rumah dinas:',NULL,17,1),
('RT','511','511','Daftar Nama Satuan Pengamanan',NULL,18,1),
('RT','512','512','Daftar Jaga/Daftar Piket',NULL,19,1),
('RT','513','513','Surat Ijin Keluar Masuk Orang/Barang',NULL,20,1),
('RT','520','520','Laporan Ketertiban dan Keamanan',NULL,21,1),
('RT','521','521','Kehilangan, kerusakan, kecelakaan, gangguan',NULL,22,1),
('RT','600','600','ADMINISTRASI PENGELOLAAN PARKIR',NULL,23,1),
('PL','0','000','Rencana Kebutuhan Barang dan Jasa',NULL,1,1),
('PL','10','010','Usulan Unit Kerja',NULL,2,1),
('PL','20','020','Rencana Kebutuhan Lembaga Pusat/Daerah',NULL,3,1),
('PL','100','100','Berkas Pengenalan',NULL,4,1),
('PL','200','200','Pengadaan Barang',NULL,5,1),
('PL','210','210','Pengadaan/pembelian barang tidak melalui lelang (pengadaan langsung)','- Usulan unit kerja
- Proses pengadaan barang
- Serah terima barang',6,1),
('PL','220','220','Pengadaan/pembelian barang melalui lelang','- Umum
- Terbatas
- Pemilihan Langsung
- Serah terima barang',7,1),
('PL','230','230','Perolehan barang melalui bantuan/hibah',NULL,8,1),
('PL','240','240','Pengadaan barang melalui tukar menukar',NULL,9,1),
('PL','250','250','Pemanfaatan barang melalui pinjam pakai',NULL,10,1),
('PL','260','260','Pemanfaatan barang melalui sewa',NULL,11,1),
('PL','270','270','Pemanfaatan barang melalui kerjasama pemanfaatan',NULL,12,1),
('PL','280','280','Pemanfaatan barang melalui bangun serah guna/bangun serah guna',NULL,13,1),
('PL','300','300','Pengadaan Jasa','Berkas pengadaan jasa oleh pihak ketiga terdiri dari berkas penawaran sampai dengan kontrak perjanjian',14,1),
('PL','400','400','Laporan kemajuan pelaksanaan belanja modal',NULL,15,1),
('PL','500','500','INVENTARISASI',NULL,16,1),
('PL','510','510','Inventarisasi Ruangan/Gedung/Bangunan',NULL,17,1),
('PL','011','011','Daftar Inventarisasi Ruangan (DIR)',NULL,18,1),
('PL','012','012','Buku Inventaris/Pembantu Inventaris Ruangan',NULL,19,1),
('PL','520','520','Inventarisasi Barang',NULL,20,1),
('PL','021','021','Daftar Opname Fisik Barang Inventaris (DOFBI)',NULL,21,1),
('PL','022','022','Daftar Inventaris Barang (DIB)',NULL,22,1),
('PL','023','023','Daftar Kartu Inventaris Barang',NULL,23,1),
('PL','024','024','Buku Inventaris/Pembantu Inventaris Barang',NULL,24,1),
('PL','530','530','Penyusunan Laporan Tahunan Inventaris BMN',NULL,25,1),
('PL','540','540','Sensus BMN',NULL,26,1),
('PL','600','600','PENYIMPANAN',NULL,27,1),
('PL','610','610','Penatausahaan Penyimpanan Barang/Publikasi',NULL,28,1),
('PL','611','611','Tanda terima/surat pengantar/surat pengiriman barang',NULL,29,1),
('PL','612','612','Surat Pernyataan harga dan mutu barang',NULL,30,1),
('PL','613','613','Berita Acara serah terima barang hasil pengadaan',NULL,31,1),
('PL','614','614','Buku Penerimaan',NULL,32,1),
('PL','615','615','Buku Persediaan barang/kartu stock barang',NULL,33,1),
('PL','616','616','Kartu barang/kartu gudang',NULL,34,1),
('PL','620','620','Penyusunan Laporan Persediaan Barang',NULL,35,1),
('PL','700','700','PENYALURAN',NULL,36,1),
('PL','710','710','Penatausahaan penyaluran barang/publikasi',NULL,37,1),
('PL','711','711','Surat Permintaan dari unit kerja/formulir permintaan',NULL,38,1),
('PL','712','712','Surat Perintah Mengeluarkan Barang (SPMB)',NULL,39,1),
('PL','713','713','Surat Perintah Mengeluarkan Barang Inventaris',NULL,40,1),
('PL','714','714','Berita Acara Serah Terima Distribusi Barang',NULL,41,1),
('PL','800','800','PENGHAPUSAN BMN',NULL,42,1),
('PL','810','810','Penghapusan Barang Bergerak/Barang Inventaris Kantor','- Nota usulan penghapusan
- Surat pembentukan panitia penghapusan
- Berita Acara pemeriksaan/penelitian barang yang akan dihapus
- Surat Izin/keputusan penghapusan barang
- Surat Keputusan Panitia Lelang
- Risalah Lelang
- Berita Acara dan Laporan Tindak Lanjut Penghapusan',43,1),
('PL','900','900','BUKTI-BUKTI KEPEMILIKAN DAN KELENGKAPAN BMN','a. Master Plan Bangunan
b. Sertifikat Tanah
c. Ijin Mendirikan Bangunan (IMB)
d. Bukti Kepemilikan Kendaraan Bermotor (BPKB)
e. Surat Tanda Nomor Kendaraan (STNK)
f. Denah/Gambar Bangunan/Instalasi Listrik, Air dan Gas',44,1),
('DL','0','000','PERENCANAAN DIKLAT',NULL,1,1),
('DL','10','010','Analisa Kebutuhan Penyelenggaran Diklat',NULL,2,1),
('DL','20','020','Sistem dan Metode',NULL,3,1),
('DL','30','030','Kurikulum',NULL,4,1),
('DL','40','040','Bahan Ajar/Modul',NULL,5,1),
('DL','50','050','Konsultasi Penyelenggaraan Diklat',NULL,6,1),
('DL','100','100','AKREDITASI LEMBAGA DIKLAT',NULL,7,1),
('DL','110','110','Surat Permohonan Akreditasi',NULL,8,1),
('DL','120','120','Laporan Hasil Verifikasi Lapangan',NULL,9,1),
('DL','130','130','Berita Acara Rapat Verifikasi',NULL,10,1),
('DL','140','140','Berita Acara Rapat Tim Penilai',NULL,11,1),
('DL','150','150','Surat Keputusan Penetapan Akreditasi',NULL,12,1),
('DL','160','160','Sertifikat Akreditasi',NULL,13,1),
('DL','170','170','Laporan Akreditasi Lembaga Diklat',NULL,14,1),
('DL','200','200','PENYELENGGARAAN DIKLAT',NULL,15,1),
('DL','210','210','Prajabatan',NULL,16,1),
('DL','220','220','Kepemimpinan',NULL,17,1),
('DL','230','230','Teknis',NULL,18,1),
('DL','240','240','Fungsional',NULL,19,1),
('DL','250','250','Evaluasi Pasca Diklat',NULL,20,1),
('DL','300','300','SERTIFIKASI SUMBER DAYA MANUSIA KEDIKLATAN','Naskah-naskah yang berkaitan dengan kegiatan sertifikasi sumber daya kediklatan',21,1),
('DL','400','400','SISTEM INFORMASI DIKLAT',NULL,22,1),
('DL','410','410','Data Lembaga Diklat',NULL,23,1),
('DL','420','420','Data Prasarana Diklat',NULL,24,1),
('DL','430','430','Data Sarana Diklat',NULL,25,1),
('DL','440','440','Data Pengelola Diklat',NULL,26,1),
('DL','450','450','Data Penyelenggara Diklat',NULL,27,1),
('DL','460','460','Data Widyaiswara',NULL,28,1),
('DL','470','470','Data Program Diklat',NULL,29,1),
('DL','500','500','REGISTRASI SERTIFIKASI/STTPL Peserta Diklat',NULL,30,1),
('DL','510','510','Surat Permohonan Kode Registrasi',NULL,31,1),
('DL','520','520','Buku Registrasi',NULL,32,1),
('DL','530','530','Surat Penyampaian Kode Registrasi',NULL,33,1),
('DL','600','600','EVALUASI PENYELENGGARAAN DIKLAT',NULL,34,1),
('DL','610','610','Evaluasi Materi Penyelenggaraan',NULL,35,1),
('DL','620','620','Evaluasi Pengajar/Instruktur/Fasilitator',NULL,36,1),
('DL','630','630','Evaluasi Peserta',NULL,37,1),
('DL','640','640','Evaluasi Sarana dan Prasarana',NULL,38,1),
('DL','650','650','Evaluasi Alumni Peserta',NULL,39,1),
('DL','660','660','Laporan Penyelenggaraan',NULL,40,1),
('DL','670','670','Evaluasi Alumni Diklat',NULL,41,1),
('PK','0','000','PENYIMPANAN DEPOSIT BAHAN PUSTAKA',NULL,1,1),
('PK','10','010','Bukti Penerimaan Koleksi Bahan Pustaka Deposit',NULL,2,1),
('PK','20','020','Administrasi Pengolahan Deposit Bahan Pustaka',NULL,3,1),
('PK','100','100','PENGADAAN BAHAN PUSTAKA',NULL,4,1),
('PK','110','110','Buku Induk Koleksi',NULL,5,1),
('PK','120','120','Daftar Buku Terseleksi',NULL,6,1),
('PK','130','130','Daftar Buku Dalam Pemesanan',NULL,7,1),
('PK','140','140','Daftar Buku Dalam Permintaan',NULL,8,1),
('PK','200','200','PENGOLAHAN BAHAN PUSTAKA',NULL,9,1),
('PK','210','210','Lembar Kerja Pengolahan Bahan Pustaka (buram, perkatalogan)',NULL,10,1),
('PK','220','220','Shell List/Jajaran Kartu Utama (master list)',NULL,11,1),
('PK','230','230','Daftar Tambahan Buku (assesion list)',NULL,12,1),
('PK','240','240','Daftar/Jajaran Kendali (subjek dan pengarang)',NULL,13,1),
('PK','300','300','LAYANAN JASA PERPUSTAKAAN DAN INFORMASI',NULL,14,1),
('PK','310','310','Data dan - 28 -tatistic anggota, pengunjung dan peminjaman bahan pustaka',NULL,15,1),
('PK','320','320','Pertanyaan, Rujukan dan Jawaban',NULL,16,1),
('PK','400','400','PRESERVASI BAHAN PUSTAKA',NULL,17,1),
('PK','410','410','Survei Kondisi Bahan Pustaka',NULL,18,1),
('PK','420','420','Reprografi Bahan Pustaka',NULL,19,1),
('PK','500','500','PEMBINAAN PERPUSTAKAAN',NULL,20,1),
('PK','510','510','Bimbingan Teknis',NULL,21,1),
('PK','520','520','Penyuluhan',NULL,22,1),
('PK','530','530','Sosialisasi',NULL,23,1),
('IF','0','000','RENCANA STRATEGIS MASTERPLAN PEMBANGUNAN SISTEM INFORMASI',NULL,1,1),
('IF','100','100','DOKUMENTASI ARSITEKTUR',NULL,2,1),
('IF','110','110','Sistem Informasi',NULL,3,1),
('IF','120','120','Sistem Aplikasi',NULL,4,1),
('IF','130','130','Infrastruktur',NULL,5,1),
('IF','200','200','PEREKAMAN DAN PEMUTAKHIRAN DATA',NULL,6,1),
('IF','210','210','Formulir Isian',NULL,7,1),
('IF','220','220','Daftar Petugas Perekaman',NULL,8,1),
('IF','230','230','Jadwal Pelaksanaan',NULL,9,1),
('IF','240','240','Laporan Hasil Perekaman dan Pemutakhiran Data',NULL,10,1),
('IF','300','300','MIGRASI SISTEM APLIKASI DATA',NULL,11,1),
('IF','400','400','DOKUMEN HOSTING',NULL,12,1),
('IF','410','410','Formulir Permintaan Hosting',NULL,13,1),
('IF','420','420','Layanan Hasil Uji Kelayakan',NULL,14,1),
('IF','430','430','Laporan Pelaksanaan Hosting',NULL,15,1),
('IF','500','500','LAYANAN BACK-UP DATA DIGITAL',NULL,16,1),
('PW','0','000','RENCANA PENGAWASAN',NULL,1,1),
('PW','10','010','Rencana Strategis Pengawasan',NULL,2,1),
('PW','20','020','Rencana Kerja Tahunan',NULL,3,1),
('PW','30','030','Rencana Kinerja Tahunan',NULL,4,1),
('PW','40','040','Penetapan Kinerja Tahunan',NULL,5,1),
('PW','50','050','Rakor Pengawasan Tingkat Nasional',NULL,6,1),
('PW','100','100','PELAKSANAAN PENGAWASAN',NULL,7,1),
('PW','110','110','Naskah-naskah yang berkaitan dengan audit mulai dari surat penugasan sampai dengan surat menyurat',NULL,8,1),
('PW','120','120','Laporan Hasil Audit (LHA), Laporan Hasil Pemeriksaan Operasional (LHPO), Laporan Hasil Evaluasi (LHE), Laporan Akuntan (LA), Laporan Auditor Independent (LAI) yang memerlukan Tindak Lanjut (TL)',NULL,9,1),
('PW','130','130','Laporan Hasil Audit Investigasi (LHAI) yang mengandung unsur Tindak Pidana Korupsi (TPK) dan memerlukan tindak lanjut',NULL,10,1),
('PW','140','140','Laporan Perkembangan Penanganan Surat Pengaduan Masyarakat',NULL,11,1),
('PW','150','150','Laporan Pemutakhiran Data',NULL,12,1),
('PW','160','160','Laporan Perkembangan BMN',NULL,13,1),
('PW','170','170','Laporan kegiatan pendampingan penyusunan laporan keuangan dan Reviu Departemen/LPND',NULL,14,1),
('PW','180','180','Good Corporate Governance (GCG)',NULL,15,1),
('TS','0','000','PENYUSUNAN RENCANA KEGIATAN BIDANG TRANSFORMASI STATISTIK (TOR)',NULL,1,1),
('TS','10','010','Transformasi Proses Bisnis Statistik',NULL,2,1),
('TS','20','020','Transformasi TIK dan Komunikasi',NULL,3,1),
('TS','30','030','Transformasi Manajemen Sumber Daya Manusia dan Kelembagaan',NULL,4,1),
('TS','100','100','PENYUSUNAN BAHAN TERKAIT TRANSFORMASI STATISTIK',NULL,5,1),
('TS','110','110','Rencana Sarana dan Prasarana Transformasi Statistik',NULL,6,1),
('TS','120','120','Statistical Bussines Frame Work and Architecture (SBFA)',NULL,7,1),
('TS','130','130','Analysis Document',NULL,8,1),
('TS','140','140','CSI',NULL,9,1),
('TS','150','150','BPR',NULL,10,1),
('TS','160','160','Sosialisasi, internalisasi, workshop terkait kegiatan transformasi',NULL,11,1),
('TS','170','170','Deliverables',NULL,12,1),
('TS','200','200','MANAJEMEN PERUBAHAN',NULL,13,1),
('TS','210','210','Steering Committee (Dewan Pengarah)',NULL,14,1),
('TS','220','220','Change Agent',NULL,15,1),
('TS','230','230','Change Leader',NULL,16,1),
('TS','240','240','Change Champion',NULL,17,1),
('TS','250','250','Working Group',NULL,18,1),
('TS','260','260','Evaluasi dan Monitoring Perkembangan Program STATCAP CERDAS; Sensus Daring/CPOC',NULL,19,1),
('TS','270','270','Sosialisasi, Internalisasi, Workshop terkait kegiatan Manajemen Perubahan, Kick of Meeting',NULL,20,1),
('TS','300','300','KETERPADUAN TRANSFORMASI',NULL,21,1),
('TS','310','310','Mendukung Implementasi Transformasi: CAPI SAKERNAS, Continous Survey',NULL,22,1),
('TS','400','400','LAPORAN TRANSFORMASI STATISTIK',NULL,23,1),
('TS','410','410','Laporan Kemajuan',NULL,24,1),
('TS','420','420','Laporan Bulanan',NULL,25,1),
('TS','430','430','Laporan Triwulanan',NULL,26,1),
('TS','440','440','Laporan Tahunan',NULL,27,1);

CREATE TABLE number_sequences (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    numbering_rule_id INT UNSIGNED NOT NULL,
    year SMALLINT UNSIGNED NOT NULL,
    current_number INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_seq(numbering_rule_id,year),
    CONSTRAINT fk_seq_rule FOREIGN KEY(numbering_rule_id) REFERENCES numbering_rules(id)
) ENGINE=InnoDB;

CREATE TABLE outgoing_letters (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agenda_number VARCHAR(20) NOT NULL,
    letter_number VARCHAR(190) NOT NULL UNIQUE,
    year SMALLINT UNSIGNED NOT NULL,
    letter_type_id INT UNSIGNED NOT NULL,
    work_team_id INT UNSIGNED NOT NULL,
    system_type ENUM('SRIKANDI','NON_SRIKANDI') NOT NULL,
    letter_date DATE NOT NULL,
    sensitivity ENUM('BIASA','PENTING','RAHASIA','SANGAT_RAHASIA') NOT NULL,
    uses_budget ENUM('Y','T') NOT NULL,
    archive_type ENUM('FASILITATIF','SUBSTANTIF') NOT NULL,
    scope_key CHAR(2) NOT NULL,
    classification_parent VARCHAR(10) NOT NULL,
    classification_child VARCHAR(10) NOT NULL,
    classification_code VARCHAR(30) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    notes TEXT NULL,
    status ENUM('ACTIVE','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
    requested_by INT UNSIGNED NOT NULL,
    cancellation_reason TEXT NULL,
    cancelled_by INT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_letter_filters(year,work_team_id,sensitivity,status),
    CONSTRAINT fk_letter_type FOREIGN KEY(letter_type_id) REFERENCES letter_types(id),
    CONSTRAINT fk_letter_team FOREIGN KEY(work_team_id) REFERENCES work_teams(id),
    CONSTRAINT fk_letter_user FOREIGN KEY(requested_by) REFERENCES users(id),
    CONSTRAINT fk_letter_cancel_user FOREIGN KEY(cancelled_by) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE audit_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT UNSIGNED NULL,
    metadata_json JSON NULL,
    ip_address VARCHAR(60) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_audit_entity(entity_type,entity_id),
    CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;

INSERT INTO work_teams(name) VALUES
('Umum, SAKIP, RB'),
('Keuangan, SPIP'),
('Kesra & Hansos'),
('Kependudukan, PPP dan Desa Cantik'),
('Neraca Wilayah Analisis Statistik'),
('Distribusi, KTIP'),
('PEK, TaPang, Horti'),
('IPD'),
('DLS, Humas dan PSS'),
('SE2026 dan EPSS'),
('Statistik Harga');

-- Rule penomoran yang sudah ditemukan pada workbook sebelumnya.
-- Mapping jenis surat -> rule masih dapat diubah oleh ADMIN dari menu Aturan Nomor.
INSERT INTO numbering_rules(code,name,unit_code,pattern) VALUES
('MAIN_62710','Aturan Utama 62710','62710','{PREFIX}-{SEQ3}/{UNIT}/{KKA}/{YEAR}'),
('SUBBAG_62711','Aturan Subbag 62711','62711','{PREFIX}-{SEQ3}/{UNIT}/{KKA}/{YEAR}'),
('FORM_PERMINTAAN','Form Permintaan (working rule)','FP-2886.EB','{SEQ3}/{UNIT}/{KKA}/{YEAR}');

INSERT INTO letter_types(code,name,numbering_rule_id) VALUES
('SURAT_PERINTAH_TUGAS','Surat Perintah/Tugas Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('SURAT_DINAS_DAERAH','Surat Dinas Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('SURAT_KETERANGAN_DAERAH','Surat Keterangan Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('UNDANGAN_EKSTERNAL','Undangan Eksternal Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('UNDANGAN_INTERNAL','Undangan Internal Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('PENGUMUMAN_DAERAH','Pengumuman Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('SURAT_KUASA_DAERAH','Surat Kuasa Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('SURAT_PENGANTAR_DAERAH','Surat Pengantar Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('BERITA_ACARA_DAERAH','Berita Acara Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('LAPORAN_DAERAH','Laporan Daerah',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('SPTJM','SPTJM',(SELECT id FROM numbering_rules WHERE code='MAIN_62710')),
('NO_SUBBAG','No. Subbag',(SELECT id FROM numbering_rules WHERE code='SUBBAG_62711')),
('FORM_PERMINTAAN_BOS','Form Permintaan',(SELECT id FROM numbering_rules WHERE code='FORM_PERMINTAAN'));

INSERT INTO letter_sensitivities(code,name,prefix,sort_order) VALUES
('BIASA','Biasa','B',1),
('PENTING','Penting','P',2),
('RAHASIA','Rahasia','R',3),
('SANGAT_RAHASIA','Sangat Rahasia','SR',4);

INSERT INTO archive_types(code,name,short_code) VALUES
('FASILITATIF','Fasilitatif','F'),
('SUBSTANTIF','Substantif','S');

-- Password demo: Admin123! dan User123!
INSERT INTO users(name,email,password_hash,role,work_team_id) VALUES
('Admin Prototype','admin@demo.local','$2y$12$thVd2VyO70X5pMSD/XKahesENG9hHC9yiNq7RlURDNeW6BE5V2NyC','ADMIN',1),
('User Prototype','user@demo.local','$2y$12$8fsTzc.oexEXWWynIVQtb.8nxijN35mfsKYRQBrWvPfvC7y4k7UKC','USER',2);
